apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - rollout-transform.yml
    
bases:
  - alice.rollout.yml
  - bob.deployment.yml


patchesStrategicMerge:
  - alice.overlay.rollout.yml
  - bob.overlay.deployment.yml

